### ISSUE TITLE
Updated descriptions in the Github repo don't seem to be reflected in the client

### ISSUE THREAD

**Issue by kirillian** [charlottejuniordevs/client#27]
I changed the description for the following issue on the API repo and the change wasn't reflected in the description card on the charlottejuniordevs challenges page:
https://github.com/charlottejuniordevs/api/issues/5

**Comment by binarymason** [comment]
I think we can close this one.  We're fetching issues directly through GitHub's API. 

¯\_(ツ)_/¯
