### ISSUE TITLE
There are some cross-site scripting issues

### ISSUE THREAD

**Issue by kirillian** [charlottejuniordevs/client#31]
My JS console shows this error:
```
XMLHttpRequest cannot load https://cltjrdevsapi-qa.herokuapp.com/credibility. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://challenges-qa.charlottejuniordevs.com' is therefore not allowed access. The response had HTTP status code 503.
```

This is indicative of a cross-site scripting problem (perhaps as simple as http vs https, but is likely a config issue that @binarymason may need to dig into)

**Comment by binarymason** [comment]
https://github.com/charlottejuniordevs/api/commit/89ae06b439eb065b4143dafa8c82cd3d0ccfeaf4 fixed this. 👍
