### ISSUE TITLE
Page not updating upon login

### ISSUE THREAD

**Issue by kamath** [charlottejuniordevs/client#68]
Pretty self explanatory - when I login, it looks like Google has accepted the OAuth authentication, but the page doesn't change to reflect the successful login

**Comment by binarymason** [comment]
This may be a false positive because of Google OAuth token taking a while to refresh.  Appears to be working now.  @andykamath can you confirm on your end?

**Comment by mattwhite8** [comment]
I can successfully log in

**Comment by binarymason** [comment]
Closing this at it appears things are working properly
